{
 "title": "Stock Prediction",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Duration Seconds Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_highr_seconds_count{instance=\"host.docker.internal:8181\",job=\"app\"}"
    }
   ]
  },
  {
   "title": "Request Duration Seconds",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_highr_seconds_sum{instance=\"host.docker.internal:8181\",job=\"app\"}"
    }
   ]
  },
  {
   "title": "HTTP Total Request ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{handler=\"/models\",instance=\"host.docker.internal:8181\",job=\"app\",method=\"POST\",status=\"2xx\"}"
    }
   ]
  },
  {
   "title": "Process Cpu",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"host.docker.internal:8181\",job=\"app\"}"
    }
   ]
  },
  {
   "title": "Request Seconds Bucket",
   "type": "histogram",
   "gridPos": { "h": 12, "w": 6, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "rate(http_request_duration_highr_seconds_bucket{instance=\"host.docker.internal:8181\",job=\"app\",le=\"0.075\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Total Object Collected",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total{generation=~\"0|1|2\",instance=\"host.docker.internal:8181\",job=\"app\"}"
    }
   ]
  },
  {
   "title": "Garbage Collector Counter",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_gc_collections_total{generation=~\"0|1|2\",instance=\"host.docker.internal:8181\",job=\"app\"}"
    }
   ]
  },
  { "type": "welcome", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 } },
  { "type": "gettingstarted", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 } },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 15, "w": 12, "x": 0, "y": 30 } },
  { "title": "Latest from the blog", "type": "news", "gridPos": { "h": 15, "w": 12, "x": 12, "y": 30 } }
 ]
}